name: release
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: '手动发布版本号（例如 1.2.3）'
        required: false
permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Restore
        run: .\nuget.exe restore .\dual-sens-manager\dual-sens-manager.csproj
      - name: Build (x64 Release)
        run: msbuild .\dual-sens-manager\dual-sens-manager.csproj /m /p:Configuration=Release /p:Platform=x64
      - name: Package outputs
        shell: pwsh
        run: |
          $configuration = 'Release'
          & .\scripts\pack-release.ps1 -Configuration $configuration

          $ver = '${{ github.event.inputs.version }}'
          if ([string]::IsNullOrWhiteSpace($ver)) { $ver = '${{ github.ref_name }}' }

          $zipSource = "DualSensManager-$configuration.zip"
          if (-not (Test-Path $zipSource)) { throw "未生成 $zipSource" }

          $zipTarget = "DualSensManager-$ver.zip"
          Move-Item -Path $zipSource -Destination $zipTarget -Force

          $sevenZipCandidates = @(
            (Join-Path $env:ProgramFiles '7-Zip\7z.exe'),
            (Join-Path ${env:ProgramFiles(x86)} '7-Zip\7z.exe')
          )
          $sevenZip = $sevenZipCandidates | Where-Object { Test-Path $_ } | Select-Object -First 1
          if (-not $sevenZip) { throw "未找到 7-Zip (7z.exe)" }

          $portableArchive = "DualSensManager-$ver-portable.7z"
          & $sevenZip a -t7z $portableArchive .\out\* -mx=9 | Out-Null

          $configPath = 'sfx-config.txt'
          @"
;!@Install@!UTF-8!
Title="DualSensManager Portable"
InstallPath="%TEMP%\DualSensManagerPortable"
RunProgram="DualSensManager.exe"
GUIMode="2"
OverwriteMode="2"
;!@InstallEnd@!
"@ | Set-Content -Path $configPath -Encoding UTF8

          $sfxCandidates = @(
            (Join-Path $env:ProgramFiles '7-Zip\7zsd.sfx'),
            (Join-Path ${env:ProgramFiles(x86)} '7-Zip\7zsd.sfx')
          )
          $sfxModule = $sfxCandidates | Where-Object { Test-Path $_ } | Select-Object -First 1
          if (-not $sfxModule) { throw "未找到 7zsd.sfx" }

          $portableExe = "DualSensManager-" + $ver + "-portable.exe"
          $copyCommand = [string]::Format('copy /b "{0}" + "{1}" + "{2}" "{3}"', $sfxModule, $configPath, $portableArchive, $portableExe)
          cmd /c $copyCommand | Out-Null

          Remove-Item $configPath, $portableArchive -Force
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            DualSensManager-${{ github.event.inputs.version || github.ref_name }}.zip
            DualSensManager-${{ github.event.inputs.version || github.ref_name }}-portable.exe
          generate_release_notes: true
          tag_name: ${{ github.event.inputs.version && format('v{0}', github.event.inputs.version) || github.ref_name }}
          target_commitish: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}